version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of greenweez / one row per products_id with price given
        columns: 
            - name: products_id
              description: pk of product table
              tests: 
                - unique
                - not_null 
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / one row per products_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id ||  '-' || pdt_id)" 
          - not_null:
              column_name: "(orders_id ||  '-' || pdt_id)" 
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
              
      - name: ship
        identifier: raw_gz_ship
        description: one row for each orders_id with shipment information
        columns: 
            - name: orders_id
              description: pk of ship table
              tests: 
                - unique
                - not_null 